import random
from typing import Optional, Dict

# Every pair here was auditioned before being added: both words checked against the
# vocabulary, and the computer's opening answer inspected (scripts/playtest.py pairs).
# A pair whose first answer is jarring makes the game look broken on the one round a
# new player is most likely to judge it on, so candidates that opened on a strange
# word were dropped rather than kept and filtered around. The comment on each line is
# the answer the computer actually gives.
STARTING_PAIRS = [
    # ── Hebrew ────────────────────────────────────────────────────────────────
    {"word1": "שמש", "word2": "ירח", "language": "he"},        # → כוכב
    {"word1": "מלך", "word2": "חייל", "language": "he"},        # → שליט
    {"word1": "כלב", "word2": "חתול", "language": "he"},        # → ארנב
    {"word1": "שבת", "word2": "קפה", "language": "he"},         # → צהריים
    {"word1": "אמא", "word2": "ילד", "language": "he"},         # → ילדה
    {"word1": "חומוס", "word2": "פיצה", "language": "he"},      # → גלידה
    {"word1": "כסף", "word2": "אהבה", "language": "he"},        # → נדיבות
    {"word1": "ילד", "word2": "זקן", "language": "he"},         # → צעיר
    {"word1": "יום", "word2": "ליל", "language": "he"},         # → חצות
    {"word1": "חם", "word2": "קר", "language": "he"},           # → קריר
    {"word1": "עיר", "word2": "כפר", "language": "he"},         # → טירה
    {"word1": "שיר", "word2": "ריקוד", "language": "he"},       # → מנגינה
    {"word1": "ספר", "word2": "ילד", "language": "he"},         # → תלמיד
    {"word1": "רופא", "word2": "חולה", "language": "he"},       # → טיפול
    {"word1": "אש", "word2": "מים", "language": "he"},          # → כיריים
    {"word1": "קרב", "word2": "ניצחון", "language": "he"},      # → תבוסה
    {"word1": "סרט", "word2": "תיאטרון", "language": "he"},     # → קולנוע
    {"word1": "חורף", "word2": "קיץ", "language": "he"},        # → סתיו
    {"word1": "בוקר", "word2": "לילה", "language": "he"},       # → יום
    {"word1": "מלח", "word2": "סוכר", "language": "he"},        # → חומץ
    {"word1": "ספר", "word2": "סרט", "language": "he"},         # → רומן
    {"word1": "מוזיקה", "word2": "ריקוד", "language": "he"},    # → מנגינה
    {"word1": "אבא", "word2": "סבא", "language": "he"},         # → סבתא
    {"word1": "כדורגל", "word2": "טניס", "language": "he"},     # → ספורט
    {"word1": "מכונית", "word2": "אופניים", "language": "he"},  # → אופנוע
    {"word1": "מחשב", "word2": "טלפון", "language": "he"},      # → נייד
    {"word1": "חייל", "word2": "שוטר", "language": "he"},       # → אזרח
    {"word1": "אריה", "word2": "חתול", "language": "he"},       # → נמר
    {"word1": "הר", "word2": "עמק", "language": "he"},          # → גבעה
    {"word1": "נהר", "word2": "ים", "language": "he"},          # → מפרץ
    {"word1": "חלון", "word2": "דלת", "language": "he"},        # → חדר
    {"word1": "שולחן", "word2": "כיסא", "language": "he"},      # → רהיט
    {"word1": "שמחה", "word2": "עצב", "language": "he"},        # → כעס
    {"word1": "זהב", "word2": "ברזל", "language": "he"},        # → נחושת
    {"word1": "תינוק", "word2": "זקן", "language": "he"},       # → נער
    {"word1": "קפה", "word2": "תה", "language": "he"},          # → סוכר
    {"word1": "תפוח", "word2": "בננה", "language": "he"},       # → אננס
    {"word1": "מלך", "word2": "מלכה", "language": "he"},        # → נסיכה

    # Added to make the game replayable: 38 openers meant a returning player
    # saw repeats within a handful of games. Generated by pairing a hand-picked
    # opener vocabulary (concrete words everyone knows) and auditioning every
    # combination automatically, then reviewing the survivors by hand.
    {"word1": "קולנוע", "word2": "רדיו", "language": "he"},                                    # -> טלוויזיה
    {"word1": "טלוויזיה", "word2": "תיאטרון", "language": "he"},                               # -> קולנוע
    {"word1": "כדורגל", "word2": "שחייה", "language": "he"},                                   # -> ספורט
    {"word1": "ברזל", "word2": "זכוכית", "language": "he"},                                    # -> פלדה
    {"word1": "ריקוד", "word2": "תיאטרון", "language": "he"},                                  # -> מחול
    {"word1": "יום", "word2": "שנה", "language": "he"},                                        # -> חודש
    {"word1": "מוזיקה", "word2": "שיר", "language": "he"},                                     # -> מנגינה
    {"word1": "אחות", "word2": "תינוק", "language": "he"},                                     # -> ילדה
    {"word1": "משחק", "word2": "רקדן", "language": "he"},                                      # -> שחקן
    {"word1": "זמר", "word2": "סופר", "language": "he"},                                       # -> משורר
    {"word1": "פחד", "word2": "שנאה", "language": "he"},                                       # -> כעס
    {"word1": "אהבה", "word2": "כעס", "language": "he"},                                       # -> קנאה
    {"word1": "דבש", "word2": "שוקולד", "language": "he"},                                     # -> מתוק
    {"word1": "טלפון", "word2": "מצלמה", "language": "he"},                                    # -> מיקרופון
    {"word1": "אמא", "word2": "תינוק", "language": "he"},                                      # -> ילדה
    {"word1": "ריצה", "word2": "שחייה", "language": "he"},                                     # -> רכיבה
    {"word1": "ילד", "word2": "מורה", "language": "he"},                                       # -> תלמיד
    {"word1": "חייל", "word2": "רופא", "language": "he"},                                      # -> קצין
    {"word1": "זמר", "word2": "ריקוד", "language": "he"},                                      # -> רקדן
    {"word1": "מכונית", "word2": "רכבת", "language": "he"},                                    # -> אוטובוס
    {"word1": "אהבה", "word2": "שיר", "language": "he"},                                       # -> געגועים
    {"word1": "תינוק", "word2": "תלמיד", "language": "he"},                                    # -> נער
    {"word1": "אח", "word2": "אמא", "language": "he"},                                         # -> אחות
    {"word1": "גשם", "word2": "דשא", "language": "he"},                                        # -> עשב
    {"word1": "גג", "word2": "דלת", "language": "he"},                                         # -> מרפסת
    {"word1": "דלת", "word2": "מטבח", "language": "he"},                                       # -> חדר
    {"word1": "חוף", "word2": "עיר", "language": "he"},                                        # -> נמל
    {"word1": "מצלמה", "word2": "רדיו", "language": "he"},                                     # -> מיקרופון
    {"word1": "יין", "word2": "מלח", "language": "he"},                                        # -> חומץ
    {"word1": "חול", "word2": "מים", "language": "he"},                                        # -> בוץ
    {"word1": "עץ", "word2": "תפוח", "language": "he"},                                        # -> תאנה
    {"word1": "אהבה", "word2": "פחד", "language": "he"},                                       # -> קנאה
    {"word1": "אופניים", "word2": "ריצה", "language": "he"},                                   # -> הליכה
    {"word1": "נחש", "word2": "ציפור", "language": "he"},                                      # -> עיט
    {"word1": "חלון", "word2": "מטבח", "language": "he"},                                      # -> חדר
    {"word1": "דבש", "word2": "מלח", "language": "he"},                                        # -> סוכר
    {"word1": "יום", "word2": "ערב", "language": "he"},                                        # -> בוקר
    {"word1": "לילה", "word2": "שעה", "language": "he"},                                       # -> חצות
    {"word1": "אגם", "word2": "שלג", "language": "he"},                                        # -> קרחון
    {"word1": "אגם", "word2": "חוף", "language": "he"},                                        # -> מפרץ
    {"word1": "קולנוע", "word2": "ריקוד", "language": "he"},                                   # -> מוזיקה
    {"word1": "כוכב", "word2": "שמש", "language": "he"},                                       # -> ירח
    {"word1": "אגם", "word2": "גשר", "language": "he"},                                        # -> נהר
    {"word1": "חוף", "word2": "נהר", "language": "he"},                                        # -> מפרץ
    {"word1": "גג", "word2": "חלון", "language": "he"},                                        # -> מרפסת
    {"word1": "גשר", "word2": "רכבת", "language": "he"},                                       # -> מנהרה
    {"word1": "מכונית", "word2": "סוס", "language": "he"},                                     # -> מנוע
    {"word1": "מלחמה", "word2": "שנאה", "language": "he"},                                     # -> פשע
    {"word1": "בכי", "word2": "פחד", "language": "he"},                                        # -> חרדה
    {"word1": "אוניברסיטה", "word2": "ילד", "language": "he"},                                 # -> סטודנט
    {"word1": "חלום", "word2": "סרט", "language": "he"},                                       # -> סיפור
    {"word1": "אבן", "word2": "חול", "language": "he"},                                        # -> חצץ
    {"word1": "סוס", "word2": "ריצה", "language": "he"},                                       # -> רכיבה
    {"word1": "חופשה", "word2": "רכבת", "language": "he"},                                     # -> נסיעה
    {"word1": "מצלמה", "word2": "תמונה", "language": "he"},                                    # -> צילום
    {"word1": "מטוס", "word2": "ספינה", "language": "he"},                                     # -> מעבורת
    {"word1": "כעס", "word2": "סערה", "language": "he"},                                       # -> זעם
    {"word1": "אמן", "word2": "מוזיאון", "language": "he"},                                    # -> פיסול
    {"word1": "גשר", "word2": "כביש", "language": "he"},                                       # -> מנהרה
    {"word1": "אדמה", "word2": "לחם", "language": "he"},                                       # -> חיטה
    {"word1": "גשם", "word2": "נהר", "language": "he"},                                        # -> שיטפון
    {"word1": "דשא", "word2": "יער", "language": "he"},                                        # -> עשב
    {"word1": "כסף", "word2": "מתנה", "language": "he"},                                       # -> ממון
    {"word1": "זיכרון", "word2": "מוזיאון", "language": "he"},                                 # -> אנדרטה
    {"word1": "מטוס", "word2": "סוס", "language": "he"},                                       # -> אופנוע
    {"word1": "דשא", "word2": "פארק", "language": "he"},                                       # -> מגרש
    {"word1": "גיבור", "word2": "סרט", "language": "he"},                                      # -> סיפור

    # ── English ───────────────────────────────────────────────────────────────
    {"word1": "ocean", "word2": "mountain", "language": "en"},   # → lake
    {"word1": "love", "word2": "war", "language": "en"},         # → quarrel
    {"word1": "fire", "word2": "ice", "language": "en"},         # → lava
    {"word1": "morning", "word2": "night", "language": "en"},    # → evening
    {"word1": "king", "word2": "peasant", "language": "en"},     # → princess
    {"word1": "silence", "word2": "thunder", "language": "en"},  # → fury
    {"word1": "city", "word2": "forest", "language": "en"},      # → park
    {"word1": "sun", "word2": "moon", "language": "en"},         # → sky
    {"word1": "past", "word2": "future", "language": "en"},      # → present
    {"word1": "cat", "word2": "dog", "language": "en"},          # → pet
    {"word1": "coffee", "word2": "sleep", "language": "en"},     # → morning
    {"word1": "gold", "word2": "silver", "language": "en"},      # → copper
    {"word1": "earth", "word2": "sky", "language": "en"},        # → heaven
    {"word1": "winter", "word2": "summer", "language": "en"},    # → autumn
    {"word1": "soldier", "word2": "peace", "language": "en"},    # → war
    {"word1": "child", "word2": "elder", "language": "en"},      # → father
    {"word1": "salt", "word2": "sugar", "language": "en"},       # → vinegar
    {"word1": "book", "word2": "film", "language": "en"},        # → story
    {"word1": "music", "word2": "dance", "language": "en"},      # → theatre
    {"word1": "river", "word2": "sea", "language": "en"},        # → shore
    {"word1": "hill", "word2": "valley", "language": "en"},      # → mountain
    {"word1": "table", "word2": "chair", "language": "en"},      # → stool
    {"word1": "gold", "word2": "iron", "language": "en"},        # → copper
    {"word1": "baby", "word2": "elder", "language": "en"},       # → mother
    {"word1": "coffee", "word2": "tea", "language": "en"},       # → cup
    {"word1": "car", "word2": "bicycle", "language": "en"},      # → motorcycle
    {"word1": "computer", "word2": "phone", "language": "en"},   # → device
    {"word1": "lion", "word2": "cat", "language": "en"},         # → animal
    {"word1": "rain", "word2": "sun", "language": "en"},         # → wind
    {"word1": "spring", "word2": "autumn", "language": "en"},    # → summer
    {"word1": "guitar", "word2": "drum", "language": "en"},      # → rhythm
    {"word1": "mountain", "word2": "desert", "language": "en"},  # → canyon
    {"word1": "knife", "word2": "spoon", "language": "en"},      # → fork
    {"word1": "bee", "word2": "flower", "language": "en"},       # → butterfly
    {"word1": "wine", "word2": "milk", "language": "en"},        # → cheese
    {"word1": "paper", "word2": "pencil", "language": "en"},     # → notebook
    {"word1": "chess", "word2": "football", "language": "en"},   # → tennis
    {"word1": "fear", "word2": "courage", "language": "en"},     # → cowardice
    {"word1": "bread", "word2": "butter", "language": "en"},     # → flour
    {"word1": "teacher", "word2": "student", "language": "en"},  # → school
    {"word1": "doctor", "word2": "nurse", "language": "en"},     # → hospital
    {"word1": "apple", "word2": "tree", "language": "en"},       # → orchard
    # Same exercise for English.
    {"word1": "teacher", "word2": "university", "language": "en"},                             # -> student
    {"word1": "child", "word2": "sister", "language": "en"},                                   # -> mother
    {"word1": "night", "word2": "time", "language": "en"},                                     # -> day
    {"word1": "mountain", "word2": "river", "language": "en"},                                 # -> valley
    {"word1": "bee", "word2": "spider", "language": "en"},                                     # -> wasp
    {"word1": "anger", "word2": "joy", "language": "en"},                                      # -> sadness
    {"word1": "book", "word2": "writer", "language": "en"},                                    # -> author
    {"word1": "apple", "word2": "garden", "language": "en"},                                   # -> orchard
    {"word1": "bed", "word2": "chair", "language": "en"},                                      # -> sofa
    {"word1": "artist", "word2": "music", "language": "en"},                                   # -> musician
    {"word1": "ice", "word2": "rain", "language": "en"},                                       # -> snow
    {"word1": "road", "word2": "sand", "language": "en"},                                      # -> gravel
    {"word1": "rain", "word2": "winter", "language": "en"},                                    # -> snow
    {"word1": "coffee", "word2": "shop", "language": "en"},                                    # -> cafe
    {"word1": "dance", "word2": "singer", "language": "en"},                                   # -> dancer
    {"word1": "iron", "word2": "silver", "language": "en"},                                    # -> copper
    {"word1": "bed", "word2": "house", "language": "en"},                                      # -> bedroom
    {"word1": "dancer", "word2": "song", "language": "en"},                                    # -> singer
    {"word1": "lion", "word2": "snake", "language": "en"},                                     # -> tiger
    {"word1": "bird", "word2": "cat", "language": "en"},                                       # -> squirrel
    {"word1": "forest", "word2": "grass", "language": "en"},                                   # -> meadow
    {"word1": "city", "word2": "school", "language": "en"},                                    # -> district
    {"word1": "morning", "word2": "sun", "language": "en"},                                    # -> sunrise
    {"word1": "butterfly", "word2": "garden", "language": "en"},                               # -> flower
    {"word1": "night", "word2": "summer", "language": "en"},                                   # -> weekend
    {"word1": "egg", "word2": "meat", "language": "en"},                                       # -> chicken
    {"word1": "evening", "word2": "restaurant", "language": "en"},                             # -> dinner
    {"word1": "farm", "word2": "horse", "language": "en"},                                     # -> barn
    {"word1": "sand", "word2": "stone", "language": "en"},                                     # -> pebble
    {"word1": "fish", "word2": "rice", "language": "en"},                                      # -> shrimp
    {"word1": "baby", "word2": "brother", "language": "en"},                                   # -> boy
    {"word1": "dog", "word2": "elephant", "language": "en"},                                   # -> animal
    {"word1": "car", "word2": "house", "language": "en"},                                      # -> garage
    {"word1": "football", "word2": "ice", "language": "en"},                                   # -> hockey
    {"word1": "painter", "word2": "picture", "language": "en"},                                # -> portrait
    {"word1": "horse", "word2": "milk", "language": "en"},                                     # -> cow
    {"word1": "coffee", "word2": "wine", "language": "en"},                                    # -> drink
    {"word1": "film", "word2": "singer", "language": "en"},                                    # -> actor
    {"word1": "apple", "word2": "cake", "language": "en"},                                     # -> pie
    {"word1": "bread", "word2": "rice", "language": "en"},                                     # -> wheat
    {"word1": "beach", "word2": "river", "language": "en"},                                    # -> shore
    {"word1": "radio", "word2": "train", "language": "en"},                                    # -> station
    {"word1": "courage", "word2": "truth", "language": "en"},                                  # -> honesty
    {"word1": "day", "word2": "holiday", "language": "en"},                                    # -> weekend
    {"word1": "bread", "word2": "sugar", "language": "en"},                                    # -> flour
    {"word1": "journey", "word2": "ship", "language": "en"},                                   # -> voyage
    {"word1": "film", "word2": "writer", "language": "en"},                                    # -> actor
    {"word1": "bird", "word2": "egg", "language": "en"},                                       # -> nest
    {"word1": "desert", "word2": "flower", "language": "en"},                                  # -> cactus
    {"word1": "bee", "word2": "milk", "language": "en"},                                       # -> honey
    {"word1": "morning", "word2": "sky", "language": "en"},                                    # -> sunrise
    {"word1": "flower", "word2": "glass", "language": "en"},                                   # -> vase
    {"word1": "bread", "word2": "chocolate", "language": "en"},                                # -> biscuit
    {"word1": "baby", "word2": "sister", "language": "en"},                                    # -> girl
    {"word1": "neighbour", "word2": "street", "language": "en"},                               # -> neighbourhood
    {"word1": "lake", "word2": "ship", "language": "en"},                                      # -> boat
    {"word1": "garden", "word2": "meat", "language": "en"},                                    # -> vegetable
    {"word1": "camera", "word2": "painter", "language": "en"},                                 # -> photographer
    {"word1": "farm", "word2": "wine", "language": "en"},                                      # -> vineyard
    {"word1": "iron", "word2": "wood", "language": "en"},                                      # -> steel
    {"word1": "grass", "word2": "sand", "language": "en"},                                     # -> gravel
    {"word1": "butterfly", "word2": "eagle", "language": "en"},                                # -> bird
    {"word1": "laughter", "word2": "love", "language": "en"},                                  # -> joy
    {"word1": "cheese", "word2": "fish", "language": "en"},                                    # -> meat
    {"word1": "chocolate", "word2": "cow", "language": "en"},                                  # -> milk
    {"word1": "cow", "word2": "elephant", "language": "en"},                                   # -> donkey
]


def get_random_pair(lang: Optional[str] = None) -> Dict:
    if lang:
        filtered = [p for p in STARTING_PAIRS if p["language"] == lang]
        if filtered:
            return random.choice(filtered)
    return random.choice(STARTING_PAIRS)
